-- =====================================================================
-- Saldos de almacén: ALMACEN_saldos_13.xlsx (292 productos) — generado por scripts/import_stock_repuestos.js
-- Pegar en Supabase → SQL Editor → Run. Se puede ejecutar varias veces: si ya se importó, no hace nada.
-- Producto existente en la sede (mismo nombre y unidad) -> SUMA la cantidad y conserva su costo.
-- Producto nuevo -> costo 0 ("Sin valorizar"). Kardex: SALDO_INICIAL con documento 'IMPORT ALMACEN_saldos_13.xlsx'.
-- =====================================================================
do $$
declare
  r record;
  ex record;
  sid text;
  saldo numeric;
  ahora text := to_char(now() at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"');
  nuevos int := 0;
  sumados int := 0;
begin
  if exists (select 1 from public.almacen where tipo = 'KARDEX' and data ->> 'tipo_movimiento' = 'SALDO_INICIAL' and data ->> 'documento' = 'IMPORT ALMACEN_saldos_13.xlsx') then
    raise notice 'El archivo ya fue importado (IMPORT ALMACEN_saldos_13.xlsx): no se hace nada.';
    return;
  end if;
  for r in select * from (values
    ('Taller Principal Aqp', '3/8"-16 MACHO ROSCAR', 'PZA', 1, 3),
    ('Taller Principal Aqp', 'ABRAZADERA BATERIA', 'PZA', 5, 4),
    ('Taller Principal Aqp', 'ABRAZADERA DE CATALIZADOR', 'PZA', 1, 5),
    ('Taller Principal Aqp', 'ABRAZADERA DE MUELLE', 'PZA', 35, 6),
    ('Taller Principal Aqp', 'ABRAZADERA POMO LIQUIDO DE FRENO', 'UND', 23, 7),
    ('Taller Principal Aqp', 'ACEITE MOTUL 7100 (20W 50)', 'LT', 33, 8),
    ('Taller Principal Aqp', 'ACEITE TRASMISION 140', 'LT', 24, 9),
    ('Taller Principal Aqp', 'AFLOJATODO', 'UND', 7, 10),
    ('Taller Principal Aqp', 'ALAMBRE N#8', 'PZA', 5, 11),
    ('Taller Principal Aqp', 'ALDABAS', 'PZA', 3, 12),
    ('Taller Principal Aqp', 'ALTERNADOR 18P (300CG)', 'PZA', 0, 13),
    ('Taller Principal Aqp', 'AMORTIGUADOR (MONOSHOP )', 'PZA', 30, 14),
    ('Taller Principal Aqp', 'AMORTIGUADOR DOBLE RESORTE', 'PZA', 6, 15),
    ('Taller Principal Aqp', 'ANTIRRESPINGO DE SOLDAR', 'PZA', 13, 16),
    ('Taller Principal Aqp', 'ARAÑA BOCAMAZA', 'PZA', 4, 17),
    ('Taller Principal Aqp', 'ARRANCADOR HHCG 250', 'PZA', 3, 18),
    ('Taller Principal Aqp', 'ARTICULACION', 'PZA', 54, 19),
    ('Taller Principal Aqp', 'ASIENTO BULL', 'PZA', 20, 20),
    ('Taller Principal Aqp', 'BAL LIQUIDO PARA RADIADOR', 'UND', 3, 21),
    ('Taller Principal Aqp', 'BALDE LIQUIDO FRENO', 'UND', 3, 22),
    ('Taller Principal Aqp', 'BARRA TELESCOPICA AZUL', 'PZA', 14, 23),
    ('Taller Principal Aqp', 'BARRA TELESCOPICA ROJO', 'PZA', 9, 24),
    ('Taller Principal Aqp', 'BASE CARDAN ( TRANSVERSAL)', 'PZA', 2, 25),
    ('Taller Principal Aqp', 'BATERIA 12V 9PLACAS', 'PZA', 1, 26),
    ('Taller Principal Aqp', 'BATERIA 500 U1R', 'UND', 10, 27),
    ('Taller Principal Aqp', 'BENDIX (300CG) 20P 3H', 'PZA', 44, 28),
    ('Taller Principal Aqp', 'BENIX', 'PZA', 44, 29),
    ('Taller Principal Aqp', 'BOBINAS', 'PZA', 91, 30),
    ('Taller Principal Aqp', 'BOCAMASA COCHE', 'PZA', 0, 31),
    ('Taller Principal Aqp', 'BOCAMAZA DELAN. PLOMO', 'PZA', 12, 32),
    ('Taller Principal Aqp', 'BOCAMAZA NEGRO', 'PZA', 11, 33),
    ('Taller Principal Aqp', 'BOCINA', 'PZA', 12, 34),
    ('Taller Principal Aqp', 'BOMBA DE FRENO (MADRE)', 'PZA', 10, 35),
    ('Taller Principal Aqp', 'BOMBA FRENO ZAPATA', 'PZA', 0, 36),
    ('Taller Principal Aqp', 'BOQUILLA DE CATALIZADOR', 'PZA', 13, 37),
    ('Taller Principal Aqp', 'BOQUILLA DE MIG 1.0', 'PZA', 4, 38),
    ('Taller Principal Aqp', 'BRIDA', 'PZA', 77, 39),
    ('Taller Principal Aqp', 'BROCA 1/8', 'PZA', 3, 40),
    ('Taller Principal Aqp', 'BUJIA', 'PZA', 35, 41),
    ('Taller Principal Aqp', 'CABALLO (CHASIS)', 'PZA', 20, 42),
    ('Taller Principal Aqp', 'CABEZAL COMPLETO', 'PZA', 1, 43),
    ('Taller Principal Aqp', 'CABLE DE ACELERADOR', 'PZA', 39, 44),
    ('Taller Principal Aqp', 'CABLE DE BATERIA NEGRO X METRO', 'PZA', 415, 45),
    ('Taller Principal Aqp', 'CABLE DE BATERIA ROJO X METRO', 'PZA', 334, 46),
    ('Taller Principal Aqp', 'CABLE DE VELOCIMETRO', 'PZA', 2, 47),
    ('Taller Principal Aqp', 'CABLE EMBRIAGUE', 'PZA', 38, 48),
    ('Taller Principal Aqp', 'CABLE EMBRIAGUE SOLO', 'PZA', 473, 49),
    ('Taller Principal Aqp', 'CABLE FRENO DE MANO', 'PZA', 12, 50),
    ('Taller Principal Aqp', 'CABLE FRENO DELANTERO', 'PZA', 37, 51),
    ('Taller Principal Aqp', 'CABLE RUSTER 1.5 M', 'PZA', 1, 52),
    ('Taller Principal Aqp', 'CABLE RUSTER 2 M', 'PZA', 2, 53),
    ('Taller Principal Aqp', 'CADENA', 'PZA', 10, 54),
    ('Taller Principal Aqp', 'CAJA FILTRO DE AIRE', 'PZA', 64, 55),
    ('Taller Principal Aqp', 'CAJA RETRO', 'PZA', 48, 56),
    ('Taller Principal Aqp', 'CAMARA 500-12', 'PZA', 18, 57),
    ('Taller Principal Aqp', 'CAÑERIA DE FRENO', 'PZA', 0, 58),
    ('Taller Principal Aqp', 'CARBON BRUSH 2PCS', 'PZA', 5, 59),
    ('Taller Principal Aqp', 'CARBURADOR ROMI', 'PZA', 24, 60),
    ('Taller Principal Aqp', 'CARBURADOR ORIGINAL', 'PZA', 15, 61),
    ('Taller Principal Aqp', 'CARDAN 1 . 10 CM', 'PZA', 105, 62),
    ('Taller Principal Aqp', 'CARDAN 50CM', 'PZA', 2, 63),
    ('Taller Principal Aqp', 'CARDAN 52.5 CM', 'PZA', 12, 64),
    ('Taller Principal Aqp', 'CARDAN 60CM', 'PZA', 20, 65),
    ('Taller Principal Aqp', 'CARDAN DE CAJA RETRO', 'PZA', 0, 66),
    ('Taller Principal Aqp', 'CASCOS BLANCOS', 'PZA', 4, 67),
    ('Taller Principal Aqp', 'CASCOS AZULES', 'PZA', 9, 68),
    ('Taller Principal Aqp', 'CATALIZADOR ARMADO', 'PZA', 32, 69),
    ('Taller Principal Aqp', 'CATALIZADOR EURO 4', 'UND', 0, 70),
    ('Taller Principal Aqp', 'CDI', 'PZA', 7, 71),
    ('Taller Principal Aqp', 'CERAMICA 8 1/2 171826', 'PZA', 21, 72),
    ('Taller Principal Aqp', 'CHANCHITO', 'PZA', 19, 73),
    ('Taller Principal Aqp', 'CHAPA CONFIGURADA', 'PZA', 0, 74),
    ('Taller Principal Aqp', 'CHAPA DE CONTACTO', 'PZA', 26, 75),
    ('Taller Principal Aqp', 'CHAPA DE TANQUE', 'PZA', 8, 76),
    ('Taller Principal Aqp', 'CHASCOSA', 'PZA', 5, 77),
    ('Taller Principal Aqp', 'CHASIS CUADRO POSTERIOR', 'PZA', 1, 78),
    ('Taller Principal Aqp', 'CILINDRO ZS 74MM', 'PZA', 0, 79),
    ('Taller Principal Aqp', 'CINTA NEGRA', 'PZA', 195, 80),
    ('Taller Principal Aqp', 'CINTILLO 4.8X300 MM', 'PZA', 7, 81),
    ('Taller Principal Aqp', 'CINTURON DE BARRA TELESCOPICA', 'PZA', 8, 82),
    ('Taller Principal Aqp', 'COCHE MINERO Z20', 'PZA', 3, 83),
    ('Taller Principal Aqp', 'CODO 1"', 'PZA', 96, 84),
    ('Taller Principal Aqp', 'CODO DE 2"', 'PZA', 50, 85),
    ('Taller Principal Aqp', 'COMANDO COMPLETO', 'PZA', 15, 86),
    ('Taller Principal Aqp', 'COMANDO DERECHO', 'PZA', 0, 87),
    ('Taller Principal Aqp', 'COMANDO IZQUIERDO', 'PZA', 0, 88),
    ('Taller Principal Aqp', 'CONTRATUERCA M10', 'PZA', 2000, 89),
    ('Taller Principal Aqp', 'COPA CENTRIFUGA', 'PZA', 5, 90),
    ('Taller Principal Aqp', 'CORONA REDUCIDA 93 CM', 'PZA', 32, 91),
    ('Taller Principal Aqp', 'CORONAS DEFECTUOSAS', 'PZA', 6, 92),
    ('Taller Principal Aqp', 'CREMALLERA COMP', 'PZA', 4, 93),
    ('Taller Principal Aqp', 'CRUCETA 20 X 50', 'PZA', 0, 94),
    ('Taller Principal Aqp', 'CULATA ZS 300CC', 'PZA', 0, 95),
    ('Taller Principal Aqp', 'DIFUSORES DE GAS DE SOLD', 'PZA', 2, 96),
    ('Taller Principal Aqp', 'DISCO DE 7"', 'PZA', 81, 97),
    ('Taller Principal Aqp', 'DISCO DE CORTE 14', 'PZA', 10, 98),
    ('Taller Principal Aqp', 'DISCO DE CORTE 4"', 'PZA', 88, 99),
    ('Taller Principal Aqp', 'DISCO DE DESBASTE 4"', 'PZA', 11, 100),
    ('Taller Principal Aqp', 'DISCO DESGASTE DE 7"', 'PZA', 14, 101),
    ('Taller Principal Aqp', 'DISCO FLAP', 'PZA', 49, 102),
    ('Taller Principal Aqp', 'EJE CORONA 37 CM ( 6D)', 'PZA', 6, 103),
    ('Taller Principal Aqp', 'EJE CORONA 73CM ( 6D)', 'PZA', 32, 104),
    ('Taller Principal Aqp', 'EJE CORONA 39CM (6D)', 'PZA', 6, 105),
    ('Taller Principal Aqp', 'EJE CORONA 41.50 (6D)', 'PZA', 1, 106),
    ('Taller Principal Aqp', 'EJE CORONA 44CM (6D)', 'PZA', 6, 107),
    ('Taller Principal Aqp', 'EJE CORONA ESTRIADO', 'PZA', 50, 108),
    ('Taller Principal Aqp', 'EJE CORONA OBSERVACIO (6D)', 'PZA', 13, 109),
    ('Taller Principal Aqp', 'EJE DE ARANQUE', 'PZA', 74, 110),
    ('Taller Principal Aqp', 'EJE DELANTERO 33CM', 'PZA', 0, 111),
    ('Taller Principal Aqp', 'EMPAQUE COMPLETO-MOTOR', 'PZA', 0, 112),
    ('Taller Principal Aqp', 'EMPAQUE CULATA', 'PZA', 7, 113),
    ('Taller Principal Aqp', 'ESCOBILLAS DE COPA 3"', 'PZA', 7, 114),
    ('Taller Principal Aqp', 'ESMALTE BLANCO', 'PZA', 1, 115),
    ('Taller Principal Aqp', 'ESPALDAR AZUL', 'PZA', 9, 116),
    ('Taller Principal Aqp', 'ESPALDAR ROJO', 'PZA', 4, 117),
    ('Taller Principal Aqp', 'ESPARRAGO 10.9 COCHE', 'PZA', 1, 118),
    ('Taller Principal Aqp', 'ESPARRAGO G10.9 (M10X50)', 'PZA', 71, 119),
    ('Taller Principal Aqp', 'ESPARRAGO G8.8 (M10X50)', 'PZA', 1600, 120),
    ('Taller Principal Aqp', 'ESPARRAGO TUERCA COCHE', 'PZA', 121, 121),
    ('Taller Principal Aqp', 'ESTRACTOR DE SEGURO DE VALVULA', 'PZA', 1, 122),
    ('Taller Principal Aqp', 'FILTRO -COMBUSTIBLE', 'PZA', 25, 123),
    ('Taller Principal Aqp', 'FILTRO AIRE CONICO', 'PZA', 4, 124),
    ('Taller Principal Aqp', 'FILTRO DE AIRE', 'PZA', 60, 125),
    ('Taller Principal Aqp', 'FOCOS LED CUADRADO', 'PZA', 33, 126),
    ('Taller Principal Aqp', 'FUSIBLE 15 AMP', 'PZA', 8, 127),
    ('Taller Principal Aqp', 'GLOSS AZUL MARINO', 'PZA', 1, 128),
    ('Taller Principal Aqp', 'GLOSS GRIS', 'PZA', 2, 129),
    ('Taller Principal Aqp', 'GLOSS NEGRO', 'PZA', 0, 130),
    ('Taller Principal Aqp', 'GOLDEN BRIDGE J505-', 'PZA', 3, 131),
    ('Taller Principal Aqp', 'GOLDEN BRIDGE MG50-6 -1.0', 'PZA', 5, 132),
    ('Taller Principal Aqp', 'GRIFO DE COMBUSTIBLE', 'PZA', 10, 133),
    ('Taller Principal Aqp', 'GUANTES BADANA', 'PZA', 1, 134),
    ('Taller Principal Aqp', 'GUANTES NYLON', 'PZA', 10, 135),
    ('Taller Principal Aqp', 'HACHES', 'PZA', 54, 136),
    ('Taller Principal Aqp', 'HOJA DE CIERRA CINTA', 'PZA', 1, 137),
    ('Taller Principal Aqp', 'INSERTO CARBURADO PARA ROSCADO', 'PZA', 2, 138),
    ('Taller Principal Aqp', 'INSERTO CARBURADO TRIANGULAR', 'PZA', 9, 139),
    ('Taller Principal Aqp', 'INSERTO CARBURADOR ROMBO', 'PZA', 7, 140),
    ('Taller Principal Aqp', 'JEBE DE FRENO', 'PZA', 192, 141),
    ('Taller Principal Aqp', 'JEBE DE MUELLE', 'PZA', 33, 142),
    ('Taller Principal Aqp', 'KIT DE FRENO', 'PZA', 24, 143),
    ('Taller Principal Aqp', 'KIT RETEN MOTOR', 'PZA', 3, 144),
    ('Taller Principal Aqp', 'LENTES DE SEGURIDAD OSCUROS', 'PZA', 12, 145),
    ('Taller Principal Aqp', 'LENTES TRASPARENTE', 'PZA', 11, 146),
    ('Taller Principal Aqp', 'LIJA PARA METAL 50-2 1/2', 'PZA', 3, 147),
    ('Taller Principal Aqp', 'LIMA REDONDA 12"', 'PZA', 1, 148),
    ('Taller Principal Aqp', 'LIMPIA CONTACTO', 'PZA', 22, 149),
    ('Taller Principal Aqp', 'LLANTA C/CAMARA 500-12', 'PZA', 6, 150),
    ('Taller Principal Aqp', 'LLANTA COMPLETA-500X12', 'PZA', 54, 151),
    ('Taller Principal Aqp', 'LLANTA DE COCHE', 'PZA', 1, 152),
    ('Taller Principal Aqp', 'LLANTA TRACTOR 500-12', 'UND', 0, 153),
    ('Taller Principal Aqp', 'LLAVE ALEN', 'PZA', 1, 154),
    ('Taller Principal Aqp', 'LLAVE TORRE', 'PZA', 1, 155),
    ('Taller Principal Aqp', 'M8 *1.25 MACHO DE ROSCAR', 'PZA', 1, 156),
    ('Taller Principal Aqp', 'MANG DE AGUA X20', 'PZA', 11, 157),
    ('Taller Principal Aqp', 'MANG COMBUSTIBLE', 'PZA', 2, 158),
    ('Taller Principal Aqp', 'MANG.CORRUGADA ABIETAX100MTS', 'PZA', 2, 159),
    ('Taller Principal Aqp', 'MANGUERA CORRUGADA', 'PZA', 1, 160),
    ('Taller Principal Aqp', 'MANGUERA RADIADOR 1/2 " (ROLLO)', 'ROLLO', 10, 161),
    ('Taller Principal Aqp', 'MANIJA EMBRIAGUE', 'PZA', 0, 162),
    ('Taller Principal Aqp', 'MANIJA FRENO', 'PZA', 0, 163),
    ('Taller Principal Aqp', 'MASCARA AZUL', 'PZA', 12, 164),
    ('Taller Principal Aqp', 'MASCARA ROJO', 'PZA', 8, 165),
    ('Taller Principal Aqp', 'MECHERO DE COBRE', 'PZA', 3, 166),
    ('Taller Principal Aqp', 'MICA DE ESMERILAR SEGPRO', 'PZA', 9, 167),
    ('Taller Principal Aqp', 'MICA PARA CARETA SOLDAR', 'PZA', 9, 168),
    ('Taller Principal Aqp', 'MOTOR ROMI', 'PZA', 36, 169),
    ('Taller Principal Aqp', 'MOTOR RONCO', 'PZA', 6, 170),
    ('Taller Principal Aqp', 'MUELLE 93CM ( 7 HOJAS)', 'PZA', 45, 171),
    ('Taller Principal Aqp', 'NIPLE 2"', 'PZA', 44, 172),
    ('Taller Principal Aqp', 'NIPLES 1"', 'PZA', 83, 173),
    ('Taller Principal Aqp', 'PALANCA FRENO DE MANO POST.', 'PZA', 82, 174),
    ('Taller Principal Aqp', 'PASTA PARA SOLDAR', 'PZA', 10, 175),
    ('Taller Principal Aqp', 'PEDAL DE ARRANQUE', 'PZA', 2, 176),
    ('Taller Principal Aqp', 'PEDAL DE CAMBIO', 'PZA', 14, 177),
    ('Taller Principal Aqp', 'PERNO 3/8 X 1/2"', 'PZA', 154, 178),
    ('Taller Principal Aqp', 'PERNO 3/8X1"', 'PZA', 400, 179),
    ('Taller Principal Aqp', 'PERNO BATERIA M6X15 (G8.8)', 'PZA', 30, 180),
    ('Taller Principal Aqp', 'PERNO CAJA RETRO M6X35', 'PZA', 114, 181),
    ('Taller Principal Aqp', 'PERNO M10X140', 'PZA', 50, 182),
    ('Taller Principal Aqp', 'PERNO M12X125 (AMARILLO)', 'PZA', 30, 183),
    ('Taller Principal Aqp', 'PERNO M12X90', 'PZA', 400, 184),
    ('Taller Principal Aqp', 'PERNO M8X100', 'PZA', 114, 185),
    ('Taller Principal Aqp', 'PERNO M8X25', 'PZA', 120, 186),
    ('Taller Principal Aqp', 'PERNO M8X50 (MITAD HILO)', 'PZA', 200, 187),
    ('Taller Principal Aqp', 'PERNO MUELLE M12X110 (G8.8)', 'UND', 116, 188),
    ('Taller Principal Aqp', 'PERNO N# 10 M6X 10 (G8.8)', 'PZA', 1820, 189),
    ('Taller Principal Aqp', 'PERNO N#10 M6X40 (G8.8)', 'UND', 94, 190),
    ('Taller Principal Aqp', 'PERNO N#10 M6X50 (G8.8)', 'PZA', 106, 191),
    ('Taller Principal Aqp', 'PERNO N#13 M8X16', 'PZA', 98, 192),
    ('Taller Principal Aqp', 'PERNO N#13 M8X25', 'PZA', 20, 193),
    ('Taller Principal Aqp', 'PERNO S.P. DELANTERO M8X100 ( G8.8)', 'PZA', 75, 194),
    ('Taller Principal Aqp', 'PIN', 'PZA', 1, 195),
    ('Taller Principal Aqp', 'PIÑON ATAQUE 11P', 'PZA', 0, 196),
    ('Taller Principal Aqp', 'PINTURA EN SPRAY BLANCO', 'PZA', 13, 197),
    ('Taller Principal Aqp', 'PINTURA EN SPRAY NEGRO', 'PZA', 8, 198),
    ('Taller Principal Aqp', 'PLAQUITAS DE CARBURO', 'PZA', 17, 199),
    ('Taller Principal Aqp', 'PLASMA CNC MAYOR', 'PZA', 7, 200),
    ('Taller Principal Aqp', 'PLASMA CNC MENOR', 'PZA', 10, 201),
    ('Taller Principal Aqp', 'PLATINA FRENO 3 HUECOS', 'PZA', 0, 202),
    ('Taller Principal Aqp', 'PLATINA DE FOCO CUADRADO', 'PZA', 142, 203),
    ('Taller Principal Aqp', 'PLATINA PARA FILTRO DE AIRE', 'PZA', 72, 204),
    ('Taller Principal Aqp', 'PLATINA SUJETADOR MUELLE', 'PZA', 20, 205),
    ('Taller Principal Aqp', 'PLATINA SWICH FRENO', 'UND', 26, 206),
    ('Taller Principal Aqp', 'PORTA DIFUSOR PARA ANTORCHA', 'PZA', 3, 207),
    ('Taller Principal Aqp', 'PORTA FUSIBLE MOTO', 'PZA', 58, 208),
    ('Taller Principal Aqp', 'PORTA RADIADOR', 'PZA', 17, 209),
    ('Taller Principal Aqp', 'PORTA RELAY', 'PZA', 237, 210),
    ('Taller Principal Aqp', 'PUNTA DE CONTACTO', 'PZA', 7, 211),
    ('Taller Principal Aqp', 'PUNTA DE CONTACTO 0.8', 'PZA', 3, 212),
    ('Taller Principal Aqp', 'PUNTA DE CONTACTO1.2', 'PZA', 11, 213),
    ('Taller Principal Aqp', 'PUNTA DE CONTACTO1.6', 'PZA', 1, 214),
    ('Taller Principal Aqp', 'RADIADOR ROMY', 'PZA', 7, 215),
    ('Taller Principal Aqp', 'RADIADOR RONCO', 'PZA', 54, 216),
    ('Taller Principal Aqp', 'RAMAL CONFIGURADO', 'PZA', 16, 217),
    ('Taller Principal Aqp', 'RAMALES SIN CONFIGURAR', 'PZA', 88, 218),
    ('Taller Principal Aqp', 'RELAY 12V', 'PZA', 343, 219),
    ('Taller Principal Aqp', 'REMOLCADOR ROMI AZUL', 'PZA', 2, 220),
    ('Taller Principal Aqp', 'REMOLCADOR RONCO AZUL', 'PZA', 1, 221),
    ('Taller Principal Aqp', 'REMOLCADOR TRANSVERSAL AZUL', 'PZA', 4, 222),
    ('Taller Principal Aqp', 'REMOLCADOR TRANSVERSAL ROJO', 'PZA', 3, 223),
    ('Taller Principal Aqp', 'RESORTE COCHE', 'PZA', 0, 224),
    ('Taller Principal Aqp', 'RESORTE DE FRENO', 'PZA', 13, 225),
    ('Taller Principal Aqp', 'RESORTE DE MUELLE', 'PZA', 37, 226),
    ('Taller Principal Aqp', 'RESORTE DE MUELLE DELGADO', 'PZA', 33, 227),
    ('Taller Principal Aqp', 'RETEN 55X75X8', 'PZA', 12, 228),
    ('Taller Principal Aqp', 'RODAJE DE COCHE', 'PZA', 3, 229),
    ('Taller Principal Aqp', 'RODAJE 30204', 'PZA', 34, 230),
    ('Taller Principal Aqp', 'RODAJE 30206', 'PZA', 10, 231),
    ('Taller Principal Aqp', 'RODAJE 32009', 'PZA', 5, 232),
    ('Taller Principal Aqp', 'RODAJE 32909', 'PZA', 20, 233),
    ('Taller Principal Aqp', 'RODAJE 6204', 'PZA', 24, 234),
    ('Taller Principal Aqp', 'RODAJE 6304', 'PZA', 16, 235),
    ('Taller Principal Aqp', 'ROLLO CAÑERIAS FRENO', 'ROLLO', 2, 236),
    ('Taller Principal Aqp', 'SELENIO', 'PZA', 8, 237),
    ('Taller Principal Aqp', 'SILICONA LIMPIA RENUEVA', 'UND', 10, 238),
    ('Taller Principal Aqp', 'SILICONA BARRA', 'UND', 6, 239),
    ('Taller Principal Aqp', 'SOPORTE DE MOTOR', 'PZA', 17, 240),
    ('Taller Principal Aqp', 'SUPER BLUE', 'PZA', 2, 241),
    ('Taller Principal Aqp', 'SUPER CUT-46', 'PZA', 6, 242),
    ('Taller Principal Aqp', 'SUPERCITO 6011 (1/8"X14")', 'PZA', 3, 243),
    ('Taller Principal Aqp', 'SUPERCITO 7018 (1/8"X14")', 'PZA', 1, 244),
    ('Taller Principal Aqp', 'SWITCH DE FRENO POSTERIOR', 'PZA', 108, 245),
    ('Taller Principal Aqp', 'TABLERO CARGUERO', 'PZA', 34, 246),
    ('Taller Principal Aqp', 'TANQUE AGUA METAL', 'PZA', 8, 247),
    ('Taller Principal Aqp', 'TANQUE DE COMBIUSTIBLE ROJO', 'PZA', 8, 248),
    ('Taller Principal Aqp', 'TANQUE DE COMBUSTIBLE AZUL', 'PZA', 9, 249),
    ('Taller Principal Aqp', 'TANQUE DE REFRIGERANTE 1/2"', 'PZA', 19, 250),
    ('Taller Principal Aqp', 'TANQUE DE REFRIGERANTE 1"', 'PZA', 3, 251),
    ('Taller Principal Aqp', 'TAPA POST. CHASIS', 'PZA', 13, 252),
    ('Taller Principal Aqp', 'TAPA CIEGA', 'PZA', 53, 253),
    ('Taller Principal Aqp', 'TAPA LATERAL (ROJO)', 'PAR', 10, 254),
    ('Taller Principal Aqp', 'TAPABARRO AZUL', 'PZA', 20, 255),
    ('Taller Principal Aqp', 'TAPABARRO ROJO', 'PZA', 9, 256),
    ('Taller Principal Aqp', 'TAPAS LATERALES (AZUL)', 'PZA', 40, 257),
    ('Taller Principal Aqp', 'TAPON DE OIDO EN BOLSA', 'PZA', 103, 258),
    ('Taller Principal Aqp', 'TERMINAL DE BATERIA', 'PZA', 358, 259),
    ('Taller Principal Aqp', 'TERMOSWITH DE VENTILADOR', 'PZA', 15, 260),
    ('Taller Principal Aqp', 'TIMON MOTO', 'PZA', 10, 261),
    ('Taller Principal Aqp', 'TIMONES', 'PZA', 0, 262),
    ('Taller Principal Aqp', 'TIP DE CONTACTO 1.2-0.045', 'PZA', 3, 263),
    ('Taller Principal Aqp', 'TIZA DE CALDELERO', 'PZA', 1, 264),
    ('Taller Principal Aqp', 'TORNILLO MASCARA T15MM', 'PZA', 70, 265),
    ('Taller Principal Aqp', 'TRAPO INDUSTRIAL X KILO', 'PZA', 3, 266),
    ('Taller Principal Aqp', 'TUERCA 3/8', 'PZA', 680, 267),
    ('Taller Principal Aqp', 'TUERCA ESPALDAR M5X44', 'PZA', 110, 268),
    ('Taller Principal Aqp', 'TUERCA M10', 'PZA', 2000, 269),
    ('Taller Principal Aqp', 'TUERCA M12', 'PZA', 120, 270),
    ('Taller Principal Aqp', 'TUERCA M6', 'PZA', 320, 271),
    ('Taller Principal Aqp', 'TUERCA M8 (H. GRUESO )', 'PZA', 186, 272),
    ('Taller Principal Aqp', 'TUERCA M8 (H.FINO )', 'PZA', 130, 273),
    ('Taller Principal Aqp', 'TUERCA M8 DORADO', 'PZA', 83, 274),
    ('Taller Principal Aqp', 'UNION UNIVERSAL 1"', 'PZA', 53, 275),
    ('Taller Principal Aqp', 'VALVULA PASO 1"', 'PZA', 16, 276),
    ('Taller Principal Aqp', 'VARILLA FRENO', 'PZA', 1, 277),
    ('Taller Principal Aqp', 'VENTILADOR', 'PZA', 10, 278),
    ('Taller Principal Aqp', 'VIBRADOR', 'PZA', 0, 279),
    ('Taller Principal Aqp', 'VIDRIO TRANSPARENTE DE SOLDAR', 'PZA', 8, 280),
    ('Taller Principal Aqp', 'VIDRIOS DE SOLDAR OCURO', 'PZA', 43, 281),
    ('Taller Principal Aqp', 'VOLANDA M11', 'PZA', 1000, 282),
    ('Taller Principal Aqp', 'VOLANDA M20-M26', 'UND', 100, 283),
    ('Taller Principal Aqp', 'VOLANDA PLANA 3/8', 'PZA', 200, 284),
    ('Taller Principal Aqp', 'VOLANDA PLANA M12', 'PZA', 200, 285),
    ('Taller Principal Aqp', 'VOLANDA PLANA M6', 'PZA', 409, 286),
    ('Taller Principal Aqp', 'VOLANDA PLANA M8', 'UND', 160, 287),
    ('Taller Principal Aqp', 'VOLANDA PRESION 3/8', 'PZA', 100, 288),
    ('Taller Principal Aqp', 'VOLANDA PRESION M12', 'PZA', 180, 289),
    ('Taller Principal Aqp', 'VOLANDA PRESION M6', 'PZA', 310, 290),
    ('Taller Principal Aqp', 'VOLANDA PRESION M9.5', 'PZA', 196, 291),
    ('Taller Principal Aqp', 'VOLANTE BENDIX', 'PZA', 30, 292),
    ('Taller Principal Aqp', 'YUGO DE CAJA RETRO', 'PZA', 33, 293),
    ('Taller Principal Aqp', 'ZAPATA DE FRENO POST.', 'PZA', 3, 294)
  ) as v(sede, nombre, unidad, cantidad, fila) loop
    select id::text as id, data into ex from public.almacen
     where tipo = 'stock' and data ->> 'sede' = r.sede and upper(regexp_replace(btrim(data ->> 'nombre'), '\s+', ' ', 'g')) = r.nombre and data ->> 'unidad' = r.unidad
     limit 1;
    if found then
      sid := ex.id;
      saldo := coalesce((ex.data ->> 'cantidad')::numeric, 0) + r.cantidad;
      update public.almacen set data = data || jsonb_build_object('cantidad', saldo, 'actualizado', ahora) where tipo = 'stock' and id::text = sid;
      sumados := sumados + 1;
    else
      sid := 'REP-' || substr(md5(r.sede || '|' || r.nombre || '|' || r.unidad), 1, 16);
      saldo := r.cantidad;
      insert into public.almacen (tipo, id, data)
      values ('stock', sid, jsonb_build_object('id', sid, 'sede', r.sede, 'nombre', r.nombre, 'unidad', r.unidad, 'cantidad', r.cantidad, 'costoUnit', 0, 'actualizado', ahora))
      on conflict (tipo, id) do update set data = excluded.data;
      nuevos := nuevos + 1;
    end if;
    insert into public.almacen (tipo, id, data)
    values ('KARDEX', gen_random_uuid()::text, jsonb_build_object(
      'fecha', ahora, 'sede', r.sede, 'stock_id', sid, 'producto', r.nombre, 'unidad', r.unidad, 'tipo_movimiento', 'SALDO_INICIAL',
      'documento', 'IMPORT ALMACEN_saldos_13.xlsx', 'cantidad', r.cantidad, 'saldo', saldo, 'usuario', 'importacion'));
  end loop;
  raise notice 'Saldos importados: % nuevos · % sumados a productos existentes', nuevos, sumados;
end $$;

-- Verificación
select data ->> 'sede' as sede, count(*) as productos, sum((data ->> 'cantidad')::numeric) as unidades
  from public.almacen where tipo = 'stock' group by 1 order by 1;
